STATION_ID = 0
DATE_COLUMN = 1
AVERAGE_WINDSPEED = 4
HIGHEST_WINDSPEED = 5
HIGHEST_WINDSPEED_HOUR = 6
LOWEST_WINDSPEED = 7
LOWEST_WINDSPEED_HOUR = 8
AVERAGE_TEMPERATURE = 11
MINIMUM_TEMPERATURE = 12
MINIMUM_TEMPERATURE_HOUR = 13
MAXIMUM_TEMPERATURE = 14
MAXIMUM_TEMPERATURE_HOUR = 15

COLUMNS = [DATE_COLUMN, AVERAGE_WINDSPEED, HIGHEST_WINDSPEED, LOWEST_WINDSPEED, AVERAGE_TEMPERATURE, MINIMUM_TEMPERATURE, MAXIMUM_TEMPERATURE]